version: '3'

services:

  host:
    image: hnlaomie/draw.io
    hostname: draw_host
    networks:
      dev-net:
        ipv4_address: 172.19.0.10
    ports:
      - 8002:8080
    volumes:
      - /usr/local/data/laomie/docker/draw.io/data:/data

networks:
  dev-net:
    external: true
